/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lol;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Anurag
 */
public class mark3sem extends javax.swing.JFrame {
    
    Connection con =null;
    Statement stmt=null;
    ResultSet rs = null;

    /**
     * Creates new form mark3sem
     */
    public mark3sem() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        mark1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        mark2 = new javax.swing.JTextField();
        mark3 = new javax.swing.JTextField();
        mark4 = new javax.swing.JTextField();
        mark5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        cbg2 = new javax.swing.JComboBox<>();
        cbg3 = new javax.swing.JComboBox<>();
        cbg4 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        cbg5 = new javax.swing.JComboBox<>();
        cbg1 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tenroll = new javax.swing.JTextField();
        cbsem = new javax.swing.JComboBox<>();
        cbexam = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tlast = new javax.swing.JTextField();
        tfirst = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        stumarktab = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ttotal = new javax.swing.JTextField();
        tper = new javax.swing.JTextField();
        tres = new javax.swing.JTextField();
        tcgpa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        insertbtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        modifybtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        calculatebtn = new javax.swing.JButton();
        reportbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbsea = new javax.swing.JComboBox<>();
        tsea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbsort = new javax.swing.JComboBox<>();
        searchlabel = new javax.swing.JLabel();
        cborder = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 153));
        jLabel12.setText("  OOP");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 74, 30));

        mark1.setBackground(new java.awt.Color(102, 102, 102));
        mark1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        mark1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(mark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 70, -1));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 153));
        jLabel13.setText("EEES");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 153));
        jLabel17.setText("Data Structures");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 29));

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 153));
        jLabel20.setText("Discrete");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 30));

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 153, 153));
        jLabel21.setText("Digital Systems");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        mark2.setBackground(new java.awt.Color(102, 102, 102));
        mark2.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        mark2.setForeground(new java.awt.Color(255, 255, 255));
        mark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark2ActionPerformed(evt);
            }
        });
        jPanel10.add(mark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 70, -1));

        mark3.setBackground(new java.awt.Color(102, 102, 102));
        mark3.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        mark3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(mark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, -1));

        mark4.setBackground(new java.awt.Color(102, 102, 102));
        mark4.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        mark4.setForeground(new java.awt.Color(255, 255, 255));
        mark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark4ActionPerformed(evt);
            }
        });
        jPanel10.add(mark4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, 30));

        mark5.setBackground(new java.awt.Color(102, 102, 102));
        mark5.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        mark5.setForeground(new java.awt.Color(255, 255, 255));
        mark5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark5ActionPerformed(evt);
            }
        });
        jPanel10.add(mark5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 70, 30));

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 204));
        jLabel19.setText("Marks");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 60, 46));
        jPanel10.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 59, 460, 10));

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 204));
        jLabel22.setText("Grade");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 70, 46));

        jLabel23.setBackground(new java.awt.Color(51, 51, 51));
        jLabel23.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 204));
        jLabel23.setText("Subject");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 14, 80, 40));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 10, 210));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 12, 210));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 12, 62));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 10, 59));

        cbg2.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        cbg2.setForeground(new java.awt.Color(204, 255, 255));
        cbg2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "B+", "B", "C+", "C", "D", "E", "F" }));
        jPanel10.add(cbg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 60, -1));

        cbg3.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        cbg3.setForeground(new java.awt.Color(204, 255, 255));
        cbg3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "B+", "B", "C+", "C", "D", "E", "F" }));
        cbg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbg3ActionPerformed(evt);
            }
        });
        jPanel10.add(cbg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 60, -1));

        cbg4.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        cbg4.setForeground(new java.awt.Color(204, 255, 255));
        cbg4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "B+", "B", "C+", "C", "D", "E", "F" }));
        jPanel10.add(cbg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 60, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "B+", "B", "C+", "C", "D", "E", "F" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 60, -1));

        cbg5.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        cbg5.setForeground(new java.awt.Color(204, 255, 255));
        cbg5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "B+", "B", "C+", "C", "D", "E", "F" }));
        jPanel10.add(cbg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 60, -1));

        cbg1.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        cbg1.setForeground(new java.awt.Color(204, 255, 255));
        cbg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "B+", "B", "C+", "C", "D", "E", "F" }));
        jPanel10.add(cbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 60, -1));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("First Name");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 80, 120, 29));

        tenroll.setBackground(new java.awt.Color(102, 102, 102));
        tenroll.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tenroll.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(tenroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 230, -1));

        cbsem.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cbsem.setForeground(new java.awt.Color(204, 255, 255));
        cbsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3rd", "1st", "2nd", "4th", "5th", "6th", "7th", "8th" }));
        cbsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsemActionPerformed(evt);
            }
        });
        jPanel9.add(cbsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 190, 70, 38));

        cbexam.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cbexam.setForeground(new java.awt.Color(204, 255, 255));
        cbexam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester Exam", "Mid-Semester 1 Exam", "Mid-Semester 2 Exam" }));
        cbexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbexamActionPerformed(evt);
            }
        });
        jPanel9.add(cbexam, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 191, 230, 38));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 153));
        jLabel7.setText("Enroll No.");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 30, 120, 29));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("Last Name");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 127, 120, 29));

        tlast.setBackground(new java.awt.Color(102, 102, 102));
        tlast.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tlast.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.add(tlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 128, 230, -1));

        tfirst.setBackground(new java.awt.Color(102, 102, 102));
        tfirst.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tfirst.setForeground(new java.awt.Color(255, 255, 255));
        tfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfirstActionPerformed(evt);
            }
        });
        jPanel9.add(tfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 230, -1));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        stumarktab.setBackground(new java.awt.Color(204, 255, 255));
        stumarktab.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        stumarktab.setForeground(new java.awt.Color(51, 51, 51));
        stumarktab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enroll No.", "First Name", "Last Name", "OOP", "EEES", "Discrete", "Digital System", "Data Struture", "Total", "Percentage", "CGPA", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        stumarktab.setGridColor(new java.awt.Color(255, 255, 204));
        stumarktab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stumarktabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stumarktabMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(stumarktab);
        if (stumarktab.getColumnModel().getColumnCount() > 0) {
            stumarktab.getColumnModel().getColumn(0).setPreferredWidth(126);
        }

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 153));
        jLabel14.setText("Percentage");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 69, 120, 29));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 153));
        jLabel15.setText("Total");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 29));

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 153));
        jLabel16.setText("Result");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, 20));

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 153));
        jLabel18.setText("CGPA");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 20));

        ttotal.setBackground(new java.awt.Color(102, 102, 102));
        ttotal.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        ttotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, 30));

        tper.setBackground(new java.awt.Color(102, 102, 102));
        tper.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tper.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tper, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 80, -1));

        tres.setBackground(new java.awt.Color(102, 102, 102));
        tres.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tres.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, -1));

        tcgpa.setBackground(new java.awt.Color(102, 102, 102));
        tcgpa.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tcgpa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tcgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 80, -1));

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 204));
        jLabel24.setText("Out of 500");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 90, 30));

        jLabel27.setBackground(new java.awt.Color(51, 51, 51));
        jLabel27.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 204));
        jLabel27.setText("Out of 10");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 80, 30));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        insertbtn.setBackground(new java.awt.Color(51, 51, 51));
        insertbtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        insertbtn.setForeground(new java.awt.Color(0, 255, 204));
        insertbtn.setText("Insert");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });

        refreshbtn.setBackground(new java.awt.Color(51, 51, 51));
        refreshbtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        refreshbtn.setForeground(new java.awt.Color(0, 255, 204));
        refreshbtn.setText("Update/Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(51, 51, 51));
        deletebtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(0, 255, 204));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(51, 51, 51));
        exitbtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(0, 255, 204));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        modifybtn.setBackground(new java.awt.Color(51, 51, 51));
        modifybtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        modifybtn.setForeground(new java.awt.Color(0, 255, 204));
        modifybtn.setText("Modify");
        modifybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifybtnActionPerformed(evt);
            }
        });

        resetbtn.setBackground(new java.awt.Color(51, 51, 51));
        resetbtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(0, 255, 204));
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        calculatebtn.setBackground(new java.awt.Color(51, 51, 51));
        calculatebtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        calculatebtn.setForeground(new java.awt.Color(0, 255, 204));
        calculatebtn.setText("Calulate");
        calculatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebtnActionPerformed(evt);
            }
        });

        reportbtn.setBackground(new java.awt.Color(51, 51, 51));
        reportbtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        reportbtn.setForeground(new java.awt.Color(0, 255, 204));
        reportbtn.setText("Report");
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(calculatebtn)
                .addGap(18, 18, 18)
                .addComponent(reportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modifybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modifybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-74.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-64 (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Search");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 50));

        cbsea.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cbsea.setForeground(new java.awt.Color(204, 255, 255));
        cbsea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enroll No.", "First Name", "Last Name", "Result" }));
        jPanel2.add(cbsea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        tsea.setBackground(new java.awt.Color(102, 102, 102));
        tsea.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tsea.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tsea, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 130, 40));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Order By");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, 36));

        cbsort.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cbsort.setForeground(new java.awt.Color(204, 255, 255));
        cbsort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enroll No.", "First Name", "Last Name", "OOP", "EEES", "Discrete", "DS", "DST", "Total", "Percentage", "CGPA", " " }));
        cbsort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsortItemStateChanged(evt);
            }
        });
        cbsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsortActionPerformed(evt);
            }
        });
        jPanel2.add(cbsort, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 170, -1));

        searchlabel.setBackground(new java.awt.Color(51, 51, 0));
        searchlabel.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        searchlabel.setForeground(new java.awt.Color(0, 255, 204));
        searchlabel.setText("     SEARCH");
        searchlabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        searchlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchlabelMouseClicked(evt);
            }
        });
        jPanel2.add(searchlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, 50));

        cborder.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cborder.setForeground(new java.awt.Color(204, 255, 255));
        cborder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Desc", "Asc" }));
        cborder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cborderItemStateChanged(evt);
            }
        });
        jPanel2.add(cborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 120, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 7, 10, 127));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Sort By");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 36));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 53, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(136, 136, 136))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark2ActionPerformed

    private void mark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark4ActionPerformed

    private void mark5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark5ActionPerformed

    private void cbsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsemActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to Insert this Record ", "Student Information Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
         try{ 
         Class.forName("org.sqlite.JDBC");
         con = DriverManager.getConnection("jdbc:sqlite:stu.db");
         stmt = con.createStatement();
         String q = "Select * from stumark where enroll='"+tenroll.getText()+"';";
         rs = stmt.executeQuery(q);
         if (rs.next()){
          JOptionPane.showMessageDialog(null,"Student Record with "+tenroll.getText()+" already exists .");
          rs.close();
          stmt.close();
                
          }
         else{
            
            try{
                
                Class.forName("org.sqlite.JDBC");
                con = DriverManager.getConnection("jdbc:sqlite:stu.db");
                stmt = con.createStatement();
                String query = "INSERT  INTO stumark VALUES ('"
                +tenroll.getText()+"','"
                +tfirst.getText()+"','"
                +tlast.getText()+"',"
                +mark1.getText()+","
                +mark2.getText()+","
                +mark3.getText()+","
                +mark4.getText()+","
                +mark5.getText()+","
                +ttotal.getText()+","
                +tper.getText()+","
                +tcgpa.getText()+",'"
                +tres.getText()+"');";

                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"New Record Inserted Successfull !\n Click Update/Refresh to see the changes .");

            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Catch Message : Error in Insertion\n  Note: Please fill all TextFields with respective datatype");
            }        
            finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
            }
                        }
                 }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }  
        }
    }//GEN-LAST:event_insertbtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        try{

            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            String q = "Select * from stumark ORDER by enroll;";
            rs = stmt.executeQuery(q);
            while(rs.next()){
                String enroll= rs.getString("enroll");
                String first= rs.getString("first");
                String last= rs.getString("last");
                String oop= rs.getString("oop");
                String eees= rs.getString("eees");
                String discrete= rs.getString("discrete");
                String ds= rs.getString("ds");
                String dst= rs.getString("dst");
                String total= rs.getString("total");
                String percent= rs.getString("percent");
                String cgpa= rs.getString("cgpa");
                String result= rs.getString("result");
                

                model.addRow( new Object[] {enroll,first,last,oop,eees,discrete,ds,dst,total,percent,cgpa,result});
                  
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }        
        finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();

        if(stumarktab.getSelectedRowCount()==1)
        {
            JFrame frame = new JFrame("Delete");
            if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to Delete this Record ", "Student Marks Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
            {
                try{
                    String genroll=tenroll.getText();
                    Class.forName("org.sqlite.JDBC");
                    con = DriverManager.getConnection("jdbc:sqlite:stu.db");
                    stmt = con.createStatement();
                    String query = "DELETE FROM stumark WHERE enroll='"+genroll+"';";
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(null,"Record Deleted");

                    model.removeRow(stumarktab.getSelectedRow());
                }

                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Error in Deletion");
                }        
                finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }

            }
        }
        else if(stumarktab.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(this, "Table is Empty ");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please Select a Row to Delete it ");
        }

    }//GEN-LAST:event_deletebtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit ", "Student Marks Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }

    }//GEN-LAST:event_exitbtnActionPerformed

    private void modifybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifybtnActionPerformed
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to Change this Record ", "Student Information Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
            try{
                String genroll=tenroll.getText();
                Class.forName("org.sqlite.JDBC");
                con = DriverManager.getConnection("jdbc:sqlite:stu.db");
                stmt = con.createStatement();
                String query = "UPDATE stumark SET enroll = '"
                +tenroll.getText()+"',first='"
                +tfirst.getText()+"',last='"
                +tlast.getText()+"',oop="
                +mark1.getText()+",eees="
                +mark2.getText()+",discrete="
                +mark3.getText()+",ds="
                +mark4.getText()+",dst="
                +mark5.getText()+",total="
                +ttotal.getText()+",percent="
                +tper.getText()+",cgpa="
                +tcgpa.getText()+",result='"
                +tres.getText()+"' WHERE enroll = '"+tenroll.getText()+"';";

                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"Record Successfully Updated !\n Click Update/Refresh to see the changes .");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Catch Message : Error in Modifying record");
            }        
            finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
        }
    }//GEN-LAST:event_modifybtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
        tenroll.setText(null);
        tfirst.setText(null);
        tlast.setText(null);
        
        ttotal.setText(null);
        tper.setText(null);
        tres.setText(null);
        tcgpa.setText(null);
        //cbsem.setSelectedItem(null);
        //cbexam.setSelectedIndex(0);
        
        cbg1.setSelectedItem(null);
        cbg2.setSelectedItem(null);
        cbg3.setSelectedItem(null);
        cbg4.setSelectedItem(null);
        cbg5.setSelectedItem(null);
        
        mark1.setText(null);
        mark2.setText(null);
        mark3.setText(null);
        mark4.setText(null);
        mark5.setText(null);

        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
    }//GEN-LAST:event_resetbtnActionPerformed

    private void stumarktabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stumarktabMouseClicked
      DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
      try{
      String tbenroll =model.getValueAt(stumarktab.getSelectedRow(),0).toString();
      String tbfirst =model.getValueAt(stumarktab.getSelectedRow(),1).toString();
      String tblast =model.getValueAt(stumarktab.getSelectedRow(),2).toString();
      
      String tbmark1 =model.getValueAt(stumarktab.getSelectedRow(),3).toString();
      String tbmark2 =model.getValueAt(stumarktab.getSelectedRow(),4).toString();
      String tbmark3 =model.getValueAt(stumarktab.getSelectedRow(),5).toString();
      String tbmark4 =model.getValueAt(stumarktab.getSelectedRow(),6).toString();
      String tbmark5 =model.getValueAt(stumarktab.getSelectedRow(),7).toString();
      
      String tbtotal =model.getValueAt(stumarktab.getSelectedRow(),8).toString();
      String tbper =model.getValueAt(stumarktab.getSelectedRow(),9).toString();
      String tbcgpa =model.getValueAt(stumarktab.getSelectedRow(),10).toString();
      String tbres =model.getValueAt(stumarktab.getSelectedRow(),11).toString();
      
      
      
      tenroll.setText(tbenroll);
      tfirst.setText(tbfirst);
      tlast.setText(tblast);
      mark1.setText(tbmark1);
      mark2.setText(tbmark2);
      mark3.setText(tbmark3);
      mark4.setText(tbmark4);
      mark5.setText(tbmark5);
      
      ttotal.setText(tbtotal);
      tres.setText(tbres);
      tper.setText(tbper);
      tcgpa.setText(tbcgpa);
      
      
      cbg1.setSelectedIndex(0);
      cbg2.setSelectedIndex(0);
      cbg3.setSelectedIndex(0);
      cbg4.setSelectedIndex(0);
      cbg5.setSelectedIndex(0);
      }
      
      catch(Exception e){
        String tbenroll =model.getValueAt(stumarktab.getSelectedRow(),0).toString();
        String tbfirst =model.getValueAt(stumarktab.getSelectedRow(),1).toString();
        String tblast =model.getValueAt(stumarktab.getSelectedRow(),2).toString();
        
        tenroll.setText(tbenroll);
        tfirst.setText(tbfirst);
        tlast.setText(tblast);
        
        ttotal.setText(null);
        tper.setText(null);
        tres.setText(null);
        tcgpa.setText(null);
        //cbsem.setSelectedItem(null);
        //cbexam.setSelectedIndex(0);
        
        cbg1.setSelectedItem(null);
        cbg2.setSelectedItem(null);
        cbg3.setSelectedItem(null);
        cbg4.setSelectedItem(null);
        cbg5.setSelectedItem(null);
        
        mark1.setText(null);
        mark2.setText(null);
        mark3.setText(null);
        mark4.setText(null);
        mark5.setText(null);
        
        JOptionPane.showMessageDialog(null,"Alert ! - Marks aren't assigned to this Student . \n Fill Marks , Calulate & then Click Modify to see further Reports and Marksheet .");
        }
              finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
    }//GEN-LAST:event_stumarktabMouseClicked

    private void cbg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbg3ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void cbexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbexamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbexamActionPerformed

    private void tfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfirstActionPerformed

    private void calculatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebtnActionPerformed
      
        String gsub1= mark1.getText();
        double sub1=Double.parseDouble(gsub1);
        
        String gsub2= mark2.getText();
        double sub2=Double.parseDouble(gsub2);
        
        String gsub3= mark3.getText();
        double sub3=Double.parseDouble(gsub3); 
        
        String gsub4= mark4.getText();
        double sub4=Double.parseDouble(gsub4); 
        
        String gsub5= mark5.getText();
        double sub5=Double.parseDouble(gsub5); 
        
        double total=(sub1+sub2+sub3+sub4+sub5);
        ttotal.setText(String.valueOf(total));
        


 
        double per1=(((total)/500)*100);
        double per = Math.round(per1 * 100.0) / 100.0;
        tper.setText(String.valueOf(per));       
        
        if (per>=33){
            tres.setText("Passed");
        }else if (per<33){
            tres.setText("Failed");
        }
        
        double cgpa1=((per/10)-0.25);
        double cgpa = Math.round(cgpa1 * 100.0) / 100.0;
        tcgpa.setText(String.valueOf(cgpa)); 
        
        
        
        if (sub1>=90){
            cbg1.setSelectedItem("A+");
        }
        else if(sub1<90 && sub1>=85){
            cbg1.setSelectedItem("A");
        }
        else if(sub1<85 && sub1>=75){
            cbg1.setSelectedItem("B+");
        }       
        else if(sub1<75 && sub1>=70){
            cbg1.setSelectedItem("B");
        }           
        else if(sub1<70 && sub1>=60){
            cbg1.setSelectedItem("C+");
        }
        else if(sub1<60 && sub1>=55){
            cbg1.setSelectedItem("C");
        }       
        else if(sub1<55 && sub1>=45){
            cbg1.setSelectedItem("D");
        }
        else if(sub1<45 && sub1>=33){
            cbg1.setSelectedItem("E");
        }
        else if(sub1<33){
            cbg1.setSelectedItem("F");
        }        
 
        if (sub2>=90){
            cbg2.setSelectedItem("A+");
        }
        else if(sub2<90 && sub2>=85){
            cbg2.setSelectedItem("A");
        }
        else if(sub2<85 && sub2>=75){
            cbg2.setSelectedItem("B+");
        }       
        else if(sub2<75 && sub2>=70){
            cbg2.setSelectedItem("B");
        }           
        else if(sub2<70 && sub2>=60){
            cbg2.setSelectedItem("C+");
        }
        else if(sub2<60 && sub2>=55){
            cbg2.setSelectedItem("C");
        }       
        else if(sub2<55 && sub2>=45){
            cbg2.setSelectedItem("D");
        }
        else if(sub2<45 && sub2>=33){
            cbg2.setSelectedItem("E");
        }
        else if(sub2<33){
            cbg2.setSelectedItem("F");
        }
        
        if (sub3>=90){
            cbg3.setSelectedItem("A+");
        }
        else if(sub3<90 && sub3>=85){
            cbg3.setSelectedItem("A");
        }
        else if(sub3<85 && sub3>=75){
            cbg3.setSelectedItem("B+");
        }       
        else if(sub3<75 && sub3>=70){
            cbg3.setSelectedItem("B");
        }           
        else if(sub3<70 && sub3>=60){
            cbg3.setSelectedItem("C+");
        }
        else if(sub3<60 && sub3>=55){
            cbg3.setSelectedItem("C");
        }       
        else if(sub3<55 && sub3>=45){
            cbg3.setSelectedItem("D");
        }
        else if(sub3<45 && sub3>=33){
            cbg3.setSelectedItem("E");
        }
        else if(sub3<33){
            cbg3.setSelectedItem("F");
        } 

        if (sub4>=90){
            cbg4.setSelectedItem("A+");
        }
        else if(sub4<90 && sub4>=85){
            cbg4.setSelectedItem("A");
        }
        else if(sub4<85 && sub4>=75){
            cbg4.setSelectedItem("B+");
        }       
        else if(sub4<75 && sub4>=70){
            cbg4.setSelectedItem("B");
        }           
        else if(sub4<70 && sub4>=60){
            cbg4.setSelectedItem("C+");
        }
        else if(sub4<60 && sub4>=55){
            cbg4.setSelectedItem("C");
        }       
        else if(sub4<55 && sub4>=45){
            cbg4.setSelectedItem("D");
        }
        else if(sub4<45 && sub4>=33){
            cbg4.setSelectedItem("E");
        }
        else if(sub4<33){
            cbg4.setSelectedItem("F");
        } 
 
        if (sub5>90){
            cbg5.setSelectedItem("A+");
        }
        else if(sub5<90 && sub5>=85){
            cbg5.setSelectedItem("A");
        }
        else if(sub5<85 && sub5>=75){
            cbg5.setSelectedItem("B+");
        }       
        else if(sub5<75 && sub5>=70){
            cbg5.setSelectedItem("B");
        }           
        else if(sub5<70 && sub5>=60){
            cbg5.setSelectedItem("C+");
        }
        else if(sub5<60 && sub5>=55){
            cbg5.setSelectedItem("C");
        }       
        else if(sub5<55 && sub5>=45){
            cbg5.setSelectedItem("D");
        }
        else if(sub5<45 && sub5>=33){
            cbg5.setSelectedItem("E");
        }
        else if(sub5<33){
            cbg5.setSelectedItem("F");
        }        
        
        
        
    }//GEN-LAST:event_calculatebtnActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit ", "Student Marks Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //teacherdash w = new teacherdash();
        //w.setVisible(true);   
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cbsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsortActionPerformed

    private void searchlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlabelMouseClicked
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
        int len= tsea.getText().length();
      if(len==0){
        JOptionPane.showMessageDialog(null,"Search Box is Empty . ");
      }
      else{
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        
        try{

            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            if(cbsea.getSelectedItem().equals("Enroll No.")){
            String q = "Select * from stumark WHERE enroll LIKE '%"+tsea.getText()+"%' ;";
            rs = stmt.executeQuery(q);
            }else if(cbsea.getSelectedItem().equals("First Name")){
            String q = "Select * from stumark WHERE first LIKE '%"+tsea.getText()+"%' ;";
            rs = stmt.executeQuery(q);                
            }else if(cbsea.getSelectedItem().equals("Last Name")){
            String q = "Select * from stumark WHERE last LIKE '%"+tsea.getText()+"%' ;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsea.getSelectedItem().equals("Result")){
            String q = "Select * from stumark WHERE result LIKE '%"+tsea.getText()+"%' ;";
            rs = stmt.executeQuery(q);                 
            }else{
                JOptionPane.showMessageDialog(null,"Select sort by what and then order (asc/desc)");
            }
            while(rs.next()){
                String enroll= rs.getString("enroll");
                String first= rs.getString("first");
                String last= rs.getString("last");
                String oop= rs.getString("oop");
                String eees= rs.getString("eees");
                String discrete= rs.getString("discrete");
                String ds= rs.getString("ds");
                String dst= rs.getString("dst");
                String total= rs.getString("total");
                String percent= rs.getString("percent");
                String cgpa= rs.getString("cgpa");
                String result= rs.getString("result");
                

                model.addRow( new Object[] {enroll,first,last,oop,eees,discrete,ds,dst,total,percent,cgpa,result});
            }
            rs.close();
            stmt.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }  
               
        finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
        
      }
       
    }//GEN-LAST:event_searchlabelMouseClicked

    private void cbsortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsortItemStateChanged

    }//GEN-LAST:event_cbsortItemStateChanged

    private void cborderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cborderItemStateChanged
    if(cborder.getSelectedItem().equals("Desc")){
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        try{

            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            if(cbsort.getSelectedItem().equals("Enroll No.")){
            String q = "Select * from stumark ORDER by enroll desc ;";
            rs = stmt.executeQuery(q);
            }else if(cbsort.getSelectedItem().equals("First Name")){
            String q = "Select * from stumark ORDER by first desc;";
            rs = stmt.executeQuery(q);                
            }else if(cbsort.getSelectedItem().equals("Last Name")){
            String q = "Select * from stumark ORDER by last desc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("OOP")){
            String q = "Select * from stumark ORDER by oop desc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("EEES")){
            String q = "Select * from stumark ORDER by eees desc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("Discrete")){
            String q = "Select * from stumark ORDER by discrete desc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("DS")){
            String q = "Select * from stumark ORDER by ds desc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("DST")){
            String q = "Select * from stumark ORDER by dst desc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("Total")){
            String q = "Select * from stumark ORDER by total desc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("Percentage")){
            String q = "Select * from stumark ORDER by percent desc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("CGPA")){
            String q = "Select * from stumark ORDER by cgpa desc;";
            rs = stmt.executeQuery(q);                                  
            }else{
            String q = "Select * from stumark ORDER by EEES desc;";
            rs = stmt.executeQuery(q); 
            }
            while(rs.next()){
                String enroll= rs.getString("enroll");
                String first= rs.getString("first");
                String last= rs.getString("last");
                String oop= rs.getString("oop");
                String eees= rs.getString("eees");
                String discrete= rs.getString("discrete");
                String ds= rs.getString("ds");
                String dst= rs.getString("dst");
                String total= rs.getString("total");
                String percent= rs.getString("percent");
                String cgpa= rs.getString("cgpa");
                String result= rs.getString("result");
                

                model.addRow( new Object[] {enroll,first,last,oop,eees,discrete,ds,dst,total,percent,cgpa,result});
            }
            rs.close();
            stmt.close();
        }
        catch(Exception e){
            
        }
                
        finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
    }else if(cborder.getSelectedItem().equals("Asc")){
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        try{
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            if(cbsort.getSelectedItem().equals("Enroll No.")){
            String q = "Select * from stumark ORDER by enroll asc ;";
            rs = stmt.executeQuery(q);
            }else if(cbsort.getSelectedItem().equals("First Name")){
            String q = "Select * from stumark ORDER by first asc;";
            rs = stmt.executeQuery(q);                
            }else if(cbsort.getSelectedItem().equals("Last Name")){
            String q = "Select * from stumark ORDER by last asc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("OOP")){
            String q = "Select * from stumark ORDER by oop asc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("EEES")){
            String q = "Select * from stumark ORDER by eees asc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("Discrete")){
            String q = "Select * from stumark ORDER by discrete asc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("DS")){
            String q = "Select * from stumark ORDER by ds asc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("DST")){
            String q = "Select * from stumark ORDER by dst asc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("Total")){
            String q = "Select * from stumark ORDER by total asc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("Percentage")){
            String q = "Select * from stumark ORDER by percent asc;";
            rs = stmt.executeQuery(q);                 
            }else if(cbsort.getSelectedItem().equals("CGPA")){
            String q = "Select * from stumark ORDER by cgpa asc;";
            rs = stmt.executeQuery(q);                                  
            }else{
            String q = "Select * from stumark ORDER by EEES asc;";
            rs = stmt.executeQuery(q); 
            }
            while(rs.next()){
                String enroll= rs.getString("enroll");
                String first= rs.getString("first");
                String last= rs.getString("last");
                String oop= rs.getString("oop");
                String eees= rs.getString("eees");
                String discrete= rs.getString("discrete");
                String ds= rs.getString("ds");
                String dst= rs.getString("dst");
                String total= rs.getString("total");
                String percent= rs.getString("percent");
                String cgpa= rs.getString("cgpa");
                String result= rs.getString("result");
                

                model.addRow( new Object[] {enroll,first,last,oop,eees,discrete,ds,dst,total,percent,cgpa,result});
            }
            rs.close();
            stmt.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }
                
        finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
        }
    }//GEN-LAST:event_cborderItemStateChanged

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        
             
        
        new report().setVisible(true);
        report.renroll.setText(tenroll.getText());
        
            
    }//GEN-LAST:event_reportbtnActionPerformed

    private void stumarktabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stumarktabMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_stumarktabMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel model = ( DefaultTableModel ) stumarktab.getModel();
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        try{

            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            String q = "Select * from stumark ORDER by enroll;";
            rs = stmt.executeQuery(q);
            while(rs.next()){
                String enroll= rs.getString("enroll");
                String first= rs.getString("first");
                String last= rs.getString("last");
                String oop= rs.getString("oop");
                String eees= rs.getString("eees");
                String discrete= rs.getString("discrete");
                String ds= rs.getString("ds");
                String dst= rs.getString("dst");
                String total= rs.getString("total");
                String percent= rs.getString("percent");
                String cgpa= rs.getString("cgpa");
                String result= rs.getString("result");
                

                model.addRow( new Object[] {enroll,first,last,oop,eees,discrete,ds,dst,total,percent,cgpa,result});
                  
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }        
        finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
    
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mark3sem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mark3sem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mark3sem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mark3sem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mark3sem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculatebtn;
    private javax.swing.JComboBox<String> cbexam;
    private javax.swing.JComboBox<String> cbg1;
    private javax.swing.JComboBox<String> cbg2;
    private javax.swing.JComboBox<String> cbg3;
    private javax.swing.JComboBox<String> cbg4;
    private javax.swing.JComboBox<String> cbg5;
    private javax.swing.JComboBox<String> cborder;
    private javax.swing.JComboBox<String> cbsea;
    private javax.swing.JComboBox<String> cbsem;
    private javax.swing.JComboBox<String> cbsort;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton insertbtn;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField mark1;
    private javax.swing.JTextField mark2;
    private javax.swing.JTextField mark3;
    private javax.swing.JTextField mark4;
    private javax.swing.JTextField mark5;
    private javax.swing.JButton modifybtn;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JButton reportbtn;
    private javax.swing.JButton resetbtn;
    private javax.swing.JLabel searchlabel;
    private javax.swing.JTable stumarktab;
    private javax.swing.JTextField tcgpa;
    public static javax.swing.JTextField tenroll;
    private javax.swing.JTextField tfirst;
    private javax.swing.JTextField tlast;
    private javax.swing.JTextField tper;
    private javax.swing.JTextField tres;
    private javax.swing.JTextField tsea;
    private javax.swing.JTextField ttotal;
    // End of variables declaration//GEN-END:variables
}
