/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lol;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Anurag
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    Connection con =null;
    Statement stmt=null;
    ResultSet rs = null;
    
    

    
    public report() {
        

        
        initComponents();
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rsem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rdis = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        rtotal = new javax.swing.JLabel();
        rgrad = new javax.swing.JLabel();
        rds = new javax.swing.JLabel();
        rdst = new javax.swing.JLabel();
        roop = new javax.swing.JLabel();
        reees = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();
        g5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        rcgpa = new javax.swing.JLabel();
        rper = new javax.swing.JLabel();
        rresult = new javax.swing.JLabel();
        rname = new javax.swing.JLabel();
        renroll2 = new javax.swing.JLabel();
        rphone = new javax.swing.JLabel();
        rdob = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        renroll = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rgender = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        remail = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        buttonpanel = new javax.swing.JPanel();
        printbtn = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STUDENT REPORT");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Random College Of Technology  ");

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Examination November - 2020");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bachelor of Technology (Computer Science & Engineering )");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enrollment No.               :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name                         :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status            :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date of Birth              :");

        rsem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rsem.setForeground(new java.awt.Color(204, 255, 255));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("Subject Code");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 18, 89, 28));

        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("Subject Name");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 18, 96, 28));

        jLabel14.setForeground(new java.awt.Color(255, 153, 153));
        jLabel14.setText("CS-303");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 121, -1, 28));

        jLabel15.setForeground(new java.awt.Color(255, 255, 204));
        jLabel15.setText("Marks");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 18, -1, 28));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 52, 552, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 74, 12, 137));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 74, 12, 133));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 74, 12, 133));

        jLabel16.setForeground(new java.awt.Color(255, 153, 153));
        jLabel16.setText("CS-302");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 91, -1, 28));

        jLabel17.setForeground(new java.awt.Color(255, 255, 204));
        jLabel17.setText("Grade");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 28));

        jLabel18.setForeground(new java.awt.Color(255, 153, 153));
        jLabel18.setText("CS-304");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 151, -1, 28));

        jLabel19.setForeground(new java.awt.Color(255, 153, 153));
        jLabel19.setText("CS-305");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 181, -1, 28));

        jLabel20.setForeground(new java.awt.Color(255, 153, 153));
        jLabel20.setText("ES-301");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 61, -1, 28));

        jLabel13.setForeground(new java.awt.Color(153, 153, 255));
        jLabel13.setText("OOP");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 70, 20));

        jLabel21.setForeground(new java.awt.Color(153, 153, 255));
        jLabel21.setText("EEES");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 50, -1));

        jLabel22.setForeground(new java.awt.Color(153, 153, 255));
        jLabel22.setText("Discrete");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel23.setForeground(new java.awt.Color(153, 153, 255));
        jLabel23.setText("Digital Systems");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel24.setForeground(new java.awt.Color(153, 153, 255));
        jLabel24.setText("Data Structures");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, 20));

        rdis.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(rdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 47, 24));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 221, 540, 10));

        jLabel35.setForeground(new java.awt.Color(255, 255, 204));
        jLabel35.setText("Total");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 237, 74, 34));

        rtotal.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(rtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 237, 100, 28));

        rgrad.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(rgrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 48, 28));

        rds.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(rds, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 40, 20));

        rdst.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(rdst, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 122, 40, 30));

        roop.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(roop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 47, 24));

        reees.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(reees, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 47, 24));

        g1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel3.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 28, 27));

        g2.setForeground(new java.awt.Color(204, 255, 204));
        jPanel3.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 28, 21));

        g3.setForeground(new java.awt.Color(204, 255, 204));
        jPanel3.add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 28, 25));

        g4.setForeground(new java.awt.Color(204, 255, 204));
        jPanel3.add(g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 28, 23));

        g5.setForeground(new java.awt.Color(204, 255, 204));
        jPanel3.add(g5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 28, 23));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel34.setForeground(new java.awt.Color(255, 204, 204));
        jLabel34.setText("Result :");

        jLabel39.setForeground(new java.awt.Color(255, 204, 204));
        jLabel39.setText("CGPA :");

        jLabel40.setForeground(new java.awt.Color(255, 204, 204));
        jLabel40.setText("Percentage :");

        rcgpa.setForeground(new java.awt.Color(204, 255, 255));

        rper.setForeground(new java.awt.Color(204, 255, 255));

        rresult.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rresult, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rper, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rcgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rresult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rcgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rper, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rname.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rname.setForeground(new java.awt.Color(204, 255, 255));

        renroll2.setForeground(new java.awt.Color(204, 255, 255));
        renroll2.setText("Regular");

        rphone.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rphone.setForeground(new java.awt.Color(204, 255, 255));

        rdob.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rdob.setForeground(new java.awt.Color(204, 255, 255));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Semester         :");

        renroll.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        renroll.setForeground(new java.awt.Color(204, 255, 255));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Gender :");

        rgender.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rgender.setForeground(new java.awt.Color(204, 255, 255));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Email :");

        remail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        remail.setForeground(new java.awt.Color(204, 255, 255));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(renroll, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel7)
                                .addGap(39, 39, 39)
                                .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10)
                                .addGap(44, 44, 44)
                                .addComponent(rsem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel25)
                                .addGap(20, 20, 20)
                                .addComponent(rgender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel9)
                                .addGap(34, 34, 34)
                                .addComponent(rdob, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel26)
                                .addGap(23, 23, 23)
                                .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(renroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel6)
                                .addGap(17, 17, 17)
                                .addComponent(rphone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renroll, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rsem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdob, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rphone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(renroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonpanel.setBackground(new java.awt.Color(51, 51, 51));

        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonpanelLayout = new javax.swing.GroupLayout(buttonpanel);
        buttonpanel.setLayout(buttonpanelLayout);
        buttonpanelLayout.setHorizontalGroup(
            buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpanelLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        buttonpanelLayout.setVerticalGroup(
            buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printbtn)
                    .addComponent(back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
   
    }//GEN-LAST:event_jPanel1MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //String roll = lx.getText();
    
    
        
        
        try{

            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
             stmt = con.createStatement();
            String q = "select stumark.enroll , stumark.first , stumark.last , stuinfo.sem , stuinfo.gender ,stumark.oop , stumark.eees , stumark.discrete , stumark.ds ,stumark.dst , stumark.total , stumark.percent , stumark.cgpa , stumark.result , stuinfo.dob , stuinfo.phone , stuinfo.email  FROM stumark JOIN stuinfo on stuinfo.enroll=stumark.enroll WHERE stumark.enroll='"+renroll.getText()+"';";
             rs = stmt.executeQuery(q);
            if(rs.next()){
                String enroll= rs.getString("enroll");
                String first= rs.getString("first");
                String last= rs.getString("last");
                String sem= rs.getString("sem");
                String gender= rs.getString("gender");
                String oop= rs.getString("oop");
                String eees= rs.getString("eees");
                String discrete= rs.getString("discrete");
                String ds= rs.getString("ds");
                String dst= rs.getString("dst");
                String total= rs.getString("total");
                String per= rs.getString("percent");
                String cgpa= rs.getString("cgpa");
                String result= rs.getString("result");
                String dob= rs.getString("dob");
                String phone= rs.getString("phone");
                String email= rs.getString("email");
                
                roop.setText(oop);
                reees.setText(eees);
                rdis.setText(discrete);
                rds.setText(ds);
                rdst.setText(dst);
                
                rname.setText(first+" "+last);
                rsem.setText(sem);
                rdob.setText(dob);
                rphone.setText(phone);
                remail.setText(email);
                rgender.setText(gender);
                
                
                rtotal.setText(total+"/500");
                rper.setText(per+" "+"%");
                rcgpa.setText(cgpa);
                rresult.setText(result);
                
                
                
                String gsub1= roop.getText();
                double sub1=Double.parseDouble(gsub1);
        
                String gsub2= reees.getText();
                double sub2=Double.parseDouble(gsub2);
        
                String gsub3= rdis.getText();
                double sub3=Double.parseDouble(gsub3); 
        
                String gsub4= rds.getText();
                double sub4=Double.parseDouble(gsub4); 
        
                String gsub5= rdst.getText();
                double sub5=Double.parseDouble(gsub5); 
                
        
                if (sub1>=90){
                    g1.setText("A+");
                }
                else if(sub1<90 && sub1>=85){
                    g1.setText("A");
                }
                else if(sub1<85 && sub1>=75){
                    g1.setText("B+");
                }       
                else if(sub1<75 && sub1>=70){
                    g1.setText("B");
                }           
                else if(sub1<70 && sub1>=60){
                    g1.setText("C+");
                }
                else if(sub1<60 && sub1>=55){
                    g1.setText("C");
                }       
                else if(sub1<55 && sub1>=45){
                    g1.setText("D");
                }
                else if(sub1<45 && sub1>=33){
                    g1.setText("E");
                }
                else if(sub1<33){
                    g1.setText("F");
                }else{
                    g1.setText("NULL");
                } 
                
                if (sub2>=90){
                    g2.setText("A+");
                }
                else if(sub2<90 && sub2>=85){
                    g2.setText("A");
                }
                else if(sub2<85 && sub2>=75){
                    g2.setText("B+");
                }       
                else if(sub2<75 && sub2>=70){
                    g2.setText("B");
                }           
                else if(sub2<70 && sub2>=60){
                    g2.setText("C+");
                }
                else if(sub2<60 && sub2>=55){
                    g2.setText("C");
                }       
                else if(sub2<55 && sub2>=45){
                    g2.setText("D");
                }
                else if(sub2<45 && sub2>=33){
                    g2.setText("E");
                }
                else if(sub2<33){
                    g2.setText("F");
                }else{
                    g2.setText("NULL");
                }
                
                if (sub3>=90){
                    g3.setText("A+");
                }
                else if(sub3<90 && sub3>=85){
                    g3.setText("A");
                }
                else if(sub3<85 && sub3>=75){
                    g3.setText("B+");
                }       
                else if(sub3<75 && sub3>=70){
                    g3.setText("B");
                }           
                else if(sub3<70 && sub3>=60){
                    g2.setText("C+");
                }
                else if(sub3<60 && sub3>=55){
                    g3.setText("C");
                }       
                else if(sub3<55 && sub3>=45){
                    g3.setText("D");
                }
                else if(sub3<45 && sub3>=33){
                    g3.setText("E");
                }
                else if(sub3<33){
                    g3.setText("F");
                }else{
                    g3.setText("NULL");
                }
 
                
                
                if (sub4>90){
                    g4.setText("A+");
                }
                else if(sub4<90 && sub4>=85){
                    g4.setText("A");
                }
                else if(sub4<85 && sub4>=75){
                    g4.setText("B+");
                }       
                else if(sub4<75 && sub4>=70){
                    g4.setText("B");
                }           
                else if(sub4<70 && sub4>=60){
                    g4.setText("C+");
                }
                else if(sub4<60 && sub4>=55){
                    g4.setText("C");
                }       
                else if(sub4<55 && sub4>=45){
                    g4.setText("D");
                }
                else if(sub4<45 && sub4>=33){
                    g4.setText("E");
                }
                else if(sub4<33){
                    g4.setText("F");
                }else{
                    g4.setText("NULL");
                }

                
                
                if (sub5>90){
                    g5.setText("A+");
                }
                else if(sub5<90 && sub5>=85){
                    g5.setText("A");
                }
                else if(sub5<85 && sub5>=75){
                    g5.setText("B+");
                }       
                else if(sub5<75 && sub5>=70){
                    g5.setText("B");
                }           
                else if(sub5<70 && sub5>=60){
                    g5.setText("C+");
                }
                else if(sub5<60 && sub5>=55){
                    g5.setText("C");
                }       
                else if(sub5<55 && sub5>=45){
                    g5.setText("D");
                }
                else if(sub5<45 && sub5>=33){
                    g5.setText("E");
                }
                else if(sub5<33){
                    g5.setText("F");
                }else{
                    g5.setText("NULL");
                }
                
                rs.close();
                stmt.close();
                
                
            }
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Either Info or Marks not Inserted by Teacher/Admin . \n Enter Marks/Info & Try Again .");
        }        
        finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
   
      
    }//GEN-LAST:event_formWindowOpened
    
    
    public void printComponenet(){
        JFrame frame = new JFrame("Print");
      if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to Print this Marksheet ? ", "Report Manager " , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
        
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Component ");

        pj.setPrintable (new Printable() {    
            public int print(Graphics pg, PageFormat pf, int pageNum){
            if (pageNum > 0){
                return Printable.NO_SUCH_PAGE;
            }

            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            jPanel1.paint(g2);
            return Printable.PAGE_EXISTS;
            }
        });
        
        
        if (pj.printDialog() == false)
        return;

        try {
            pj.print();
        } catch (PrinterException ex) {
        // handle exception
        }
      }  
}
    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed

            printComponenet();

                    
                
    }//GEN-LAST:event_printbtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
            

       
        dispose();
    }//GEN-LAST:event_backActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

      

        /* Set the Nimbus look and feel */
        
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton printbtn;
    private javax.swing.JLabel rcgpa;
    private javax.swing.JLabel rdis;
    public static javax.swing.JLabel rdob;
    private javax.swing.JLabel rds;
    private javax.swing.JLabel rdst;
    private javax.swing.JLabel reees;
    public static javax.swing.JLabel remail;
    public static javax.swing.JLabel renroll;
    public static javax.swing.JLabel renroll2;
    public static javax.swing.JLabel rgender;
    private javax.swing.JLabel rgrad;
    public static javax.swing.JLabel rname;
    private javax.swing.JLabel roop;
    private javax.swing.JLabel rper;
    public static javax.swing.JLabel rphone;
    private javax.swing.JLabel rresult;
    public static javax.swing.JLabel rsem;
    private javax.swing.JLabel rtotal;
    // End of variables declaration//GEN-END:variables
}
