/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lol;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anurag
 */


public class studentinfo extends javax.swing.JFrame {
    
    Connection con =null;
    Statement stmt=null;
    ResultSet rs = null;
    /**
     * Creates new form studentinfo
     */
    public studentinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stuinfotab = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        cbgender = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        cbsem = new javax.swing.JComboBox<>();
        temail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tlast = new javax.swing.JTextField();
        tfirst = new javax.swing.JTextField();
        tenroll = new javax.swing.JTextField();
        tdob = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        tphone = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        insertbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        insertbtn1 = new javax.swing.JButton();
        deletebtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbsea = new javax.swing.JComboBox<>();
        tsea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbsort = new javax.swing.JComboBox<>();
        searchlabel = new javax.swing.JLabel();
        cborder = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Fira Code", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 153));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-64 (1).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        stuinfotab.setBackground(new java.awt.Color(204, 255, 204));
        stuinfotab.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        stuinfotab.setForeground(new java.awt.Color(51, 51, 51));
        stuinfotab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enroll No.", "First Name", "Last Name", "Semester", "Phone No.", "Gender", "Date of Birth", "Email ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        stuinfotab.setGridColor(new java.awt.Color(255, 255, 204));
        stuinfotab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuinfotabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stuinfotab);
        if (stuinfotab.getColumnModel().getColumnCount() > 0) {
            stuinfotab.getColumnModel().getColumn(0).setPreferredWidth(56);
            stuinfotab.getColumnModel().getColumn(1).setPreferredWidth(17);
            stuinfotab.getColumnModel().getColumn(2).setPreferredWidth(19);
            stuinfotab.getColumnModel().getColumn(3).setPreferredWidth(1);
            stuinfotab.getColumnModel().getColumn(5).setPreferredWidth(7);
            stuinfotab.getColumnModel().getColumn(6).setPreferredWidth(19);
            stuinfotab.getColumnModel().getColumn(7).setPreferredWidth(136);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbgender.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cbgender.setForeground(new java.awt.Color(204, 255, 204));
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female" }));
        cbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgenderActionPerformed(evt);
            }
        });
        jPanel5.add(cbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 335, 106, -1));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(51, 51, 51));
        jTextField8.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(204, 255, 255));
        jTextField8.setText("CSE");
        jTextField8.setBorder(null);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 292, 40, 27));

        cbsem.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cbsem.setForeground(new java.awt.Color(204, 255, 204));
        cbsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3rd", "1st", "2nd", "4th", "5th", "6th", "7th", "8th" }));
        cbsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsemActionPerformed(evt);
            }
        });
        jPanel5.add(cbsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 247, 67, -1));

        temail.setBackground(new java.awt.Color(102, 102, 102));
        temail.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        temail.setForeground(new java.awt.Color(204, 255, 255));
        temail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 228, 32));

        jLabel18.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 153));
        jLabel18.setText("Date of Birth");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 150, 32));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 222, 384, 10));

        jLabel26.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 153, 153));
        jLabel26.setText("Enroll No.");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 58, 123, 32));

        jLabel27.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 153));
        jLabel27.setText("Last Name");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 160, 123, 32));

        jLabel28.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 153, 153));
        jLabel28.setText("Semester");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 244, -1, 32));

        jLabel29.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 153, 153));
        jLabel29.setText("Branch");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 288, -1, 32));

        jLabel30.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 153, 153));
        jLabel30.setText("Phone No.");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 32));

        jLabel31.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 153, 153));
        jLabel31.setText("Gender");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 332, -1, 32));

        jLabel32.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 153, 153));
        jLabel32.setText("Email ID");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 32));

        jLabel33.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 153, 153));
        jLabel33.setText("First Name");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 108, 123, 32));

        tlast.setBackground(new java.awt.Color(102, 102, 102));
        tlast.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tlast.setForeground(new java.awt.Color(204, 255, 255));
        tlast.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(tlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 162, 193, 32));

        tfirst.setBackground(new java.awt.Color(102, 102, 102));
        tfirst.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tfirst.setForeground(new java.awt.Color(204, 255, 255));
        tfirst.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(tfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 110, 193, 32));

        tenroll.setBackground(new java.awt.Color(102, 102, 102));
        tenroll.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tenroll.setForeground(new java.awt.Color(204, 255, 255));
        tenroll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(tenroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 58, 193, 32));

        tdob.setBackground(new java.awt.Color(102, 102, 102));
        tdob.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tdob.setForeground(new java.awt.Color(204, 255, 255));
        tdob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(tdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 190, 32));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 384, 10));

        tphone.setBackground(new java.awt.Color(102, 102, 102));
        tphone.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tphone.setForeground(new java.awt.Color(204, 255, 255));
        tphone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.add(tphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 193, 32));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        insertbtn.setBackground(new java.awt.Color(51, 51, 51));
        insertbtn.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        insertbtn.setForeground(new java.awt.Color(204, 255, 255));
        insertbtn.setText("Insert");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(51, 51, 51));
        updatebtn.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(204, 255, 255));
        updatebtn.setText("Update/Refresh");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(51, 51, 51));
        deletebtn.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(204, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(51, 51, 51));
        exitbtn.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(204, 255, 255));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        insertbtn1.setBackground(new java.awt.Color(51, 51, 51));
        insertbtn1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        insertbtn1.setForeground(new java.awt.Color(204, 255, 255));
        insertbtn1.setText("Modify");
        insertbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtn1ActionPerformed(evt);
            }
        });

        deletebtn1.setBackground(new java.awt.Color(51, 51, 51));
        deletebtn1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        deletebtn1.setForeground(new java.awt.Color(204, 255, 255));
        deletebtn1.setText("Reset");
        deletebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(deletebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Search");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        cbsea.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cbsea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enroll No.", "First Name", "Last Name", "Semester", "Gender" }));
        jPanel3.add(cbsea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        tsea.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        tsea.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(tsea, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 130, 30));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Fira Code", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Sort By");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, 36));

        cbsort.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cbsort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enroll No.", "First Name", "Last Name" }));
        cbsort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsortItemStateChanged(evt);
            }
        });
        cbsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsortActionPerformed(evt);
            }
        });
        jPanel3.add(cbsort, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        searchlabel.setBackground(new java.awt.Color(51, 51, 0));
        searchlabel.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        searchlabel.setForeground(new java.awt.Color(0, 255, 204));
        searchlabel.setText("     SEARCH");
        searchlabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        searchlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchlabelMouseClicked(evt);
            }
        });
        jPanel3.add(searchlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, 50));

        cborder.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        cborder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Desc", "Asc" }));
        cborder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cborderItemStateChanged(evt);
            }
        });
        jPanel3.add(cborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 7, 10, 127));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-74.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(477, 477, 477)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Fira Code", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Student Infromation :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgenderActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void cbsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsemActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
     DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();  
      JFrame frame = new JFrame("Exit");
      if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to Insert this Record ", "Student Information Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
      {
        try{ 
         Class.forName("org.sqlite.JDBC");
         con = DriverManager.getConnection("jdbc:sqlite:stu.db");
         stmt = con.createStatement();
         String q = "Select * from stuinfo where enroll='"+tenroll.getText()+"';";
         rs = stmt.executeQuery(q);
         if (rs.next()){
          JOptionPane.showMessageDialog(null,"Student Record with "+tenroll.getText()+" already exists .");

          }
         else{
           
          try{
            String genroll=tenroll.getText();
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            String query = "INSERT  INTO stuinfo VALUES ('"
                    +tenroll.getText()+"','"
                    +tfirst.getText()+"','"
                    +tlast.getText()+"','"
                    +cbsem.getSelectedItem().toString()+"','"
                    +tphone.getText()+"','"
                    +cbgender.getSelectedItem().toString()+"','"
                    +tdob.getText()+"','"
                    +temail.getText()+"');";
            
            stmt.executeUpdate(query);
            
            while(rs.next()){
                String enroll= rs.getString("enroll");
                String first= rs.getString("first");
                String last= rs.getString("last");
                String sem= rs.getString("sem");
                String phone= rs.getString("phone");
                String gender= rs.getString("gender");
                String dob= rs.getString("dob");
                String email= rs.getString("email");

            
                model.addRow( new Object[] {enroll,first,last,sem,phone,gender,dob,email});
            }
            JOptionPane.showMessageDialog(null,"New Record Inserted Successfull !\n Click Update/Refresh to see the changes .");
            
         }

         catch(Exception e){
            JOptionPane.showMessageDialog(null,"Catch Message : Error in Insertion \n Try Agian , Fill all textboxes .");
         } 
                  
          finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
                      } 
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }          
        finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }  
      }
    }//GEN-LAST:event_insertbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
    DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();
    while(model.getRowCount() > 0){
        model.removeRow(0);
        }
    try{
        
        Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
        stmt = con.createStatement();
        String q = "Select * from stuinfo order by enroll ;";
        rs = stmt.executeQuery(q);
        while(rs.next()){
            String enroll= rs.getString("enroll");
            String first= rs.getString("first");
            String last= rs.getString("last");
            String sem= rs.getString("sem");
            String phone= rs.getString("phone");
            String gender= rs.getString("gender");
            String dob= rs.getString("dob");
            String email= rs.getString("email");
            
            
            model.addRow( new Object[] {enroll,first,last,sem,phone,gender,dob,email});
            }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error in Connectivity");
    }
            
          finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
      JFrame frame = new JFrame("Exit");
      if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit ", "Student Information Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
      {
          System.exit(0);
      }
      
          
    }//GEN-LAST:event_exitbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
     DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();
     
     if(stuinfotab.getSelectedRowCount()==1)
     {
        JFrame frame = new JFrame("Delete");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to Delete this Record ", "Student Information Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
         try{
            String genroll=tenroll.getText();
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            String query = "DELETE FROM stuinfo WHERE enroll='"+genroll+"';";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Record Deleted");
            
            
            model.removeRow(stuinfotab.getSelectedRow());
         }

         catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in Deletion");
    }        
         finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
        }

        
     }
     else if(stuinfotab.getRowCount()==0)
     {
         JOptionPane.showMessageDialog(this, "Table is Empty ");
     }
     else
     {
         JOptionPane.showMessageDialog(this, "Please Select a Row to Delete it ");  
     }
         
     
    }//GEN-LAST:event_deletebtnActionPerformed

    private void stuinfotabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuinfotabMouseClicked
      DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();
      
      String tbenroll =model.getValueAt(stuinfotab.getSelectedRow(),0).toString();
      String tbfirst =model.getValueAt(stuinfotab.getSelectedRow(),1).toString();
      String tblast =model.getValueAt(stuinfotab.getSelectedRow(),2).toString();
      String tbsem =model.getValueAt(stuinfotab.getSelectedRow(),3).toString();
      String tbphone =model.getValueAt(stuinfotab.getSelectedRow(),4).toString();
      String tbgender =model.getValueAt(stuinfotab.getSelectedRow(),5).toString();
      String tbdob =model.getValueAt(stuinfotab.getSelectedRow(),6).toString();
      String tbemail =model.getValueAt(stuinfotab.getSelectedRow(),7).toString();
      
      
      
      tenroll.setText(tbenroll);
      tfirst.setText(tbfirst);
      tlast.setText(tblast);
      tphone.setText(tbphone);
      temail.setText(tbemail);
      cbsem.setSelectedItem(tbsem);
      
      
      tdob.setText(tbdob);
      cbgender.setSelectedItem(tbgender);
      
      
    }//GEN-LAST:event_stuinfotabMouseClicked

    private void insertbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtn1ActionPerformed
     DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();  
      JFrame frame = new JFrame("Exit");

      if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to Modify this Record ", "Student Information Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
      {
          try{
            //String genroll=tenroll.getText();
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            String query = "UPDATE stuinfo SET enroll = '"
                    +tenroll.getText()+"',first='"
                    +tfirst.getText()+"',last='"
                    +tlast.getText()+"',sem='"
                    +cbsem.getSelectedItem().toString()+"',phone='"
                    +tphone.getText()+"',gender='"
                    +cbgender.getSelectedItem().toString()+"',dob='"
                    +tdob.getText()+"',email='"
                    +temail.getText()+"' WHERE enroll = '"+tenroll.getText()+"';";
            
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Record Successfully Updated !\n Click Update/Refresh to see the changes .");  
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,"Catch Message : Error in Modifying record");
         }
                  
          finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
      }
    }//GEN-LAST:event_insertbtn1ActionPerformed

    private void deletebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtn1ActionPerformed
     DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel(); 
      tenroll.setText(null);
      tfirst.setText(null);
      tlast.setText(null);
      tdob.setText(null);
      tphone.setText(null);
      temail.setText(null);
      cbsem.setSelectedItem(null);
      tdob.setText(null);
      cbgender.setSelectedItem(null);
      
        while(model.getRowCount() > 0){
        model.removeRow(0);
        }
    }//GEN-LAST:event_deletebtn1ActionPerformed

    private void cbsortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsortItemStateChanged

    }//GEN-LAST:event_cbsortItemStateChanged

    private void cbsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsortActionPerformed

    private void searchlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlabelMouseClicked
        DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();
        int len= tsea.getText().length();
        
      if(len==0){
        JOptionPane.showMessageDialog(null,"Search Box is Empty . ");
      }
      else{
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        try{

            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
            stmt = con.createStatement();
            if(cbsea.getSelectedItem().equals("Enroll No.")){
                String q = "Select * from stuinfo WHERE enroll LIKE '%"+tsea.getText()+"%' ;";
                rs = stmt.executeQuery(q);
            }else if(cbsea.getSelectedItem().equals("First Name")){
                String q = "Select * from stuinfo WHERE first LIKE '%"+tsea.getText()+"%' ;";
                rs = stmt.executeQuery(q);
            }else if(cbsea.getSelectedItem().equals("Semester")){
                String q = "Select * from stuinfo WHERE sem LIKE '%"+tsea.getText()+"%' ;";
                rs = stmt.executeQuery(q);
            }else if(cbsea.getSelectedItem().equals("Last Name")){
                String q = "Select * from stuinfo WHERE last LIKE '%"+tsea.getText()+"%' ;";
                rs = stmt.executeQuery(q);
            }else if(cbsea.getSelectedItem().equals("Gender")){
                String q = "Select * from stuinfo WHERE gender LIKE '%"+tsea.getText()+"%' ;";
                rs = stmt.executeQuery(q);
            }else{
                JOptionPane.showMessageDialog(null,"Select sort by what and then order (asc/desc)");
            }
            while(rs.next()){
                String enroll= rs.getString("enroll");
                String first= rs.getString("first");
                String last= rs.getString("last");
                String sem= rs.getString("sem");
                String phone= rs.getString("phone");
                String gender= rs.getString("gender");
                String dob= rs.getString("dob");
                String email= rs.getString("email");

                model.addRow( new Object[] {enroll,first,last,sem,phone,gender,dob,email});
            }
            
            rs.close();
            stmt.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }
                
        finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
      }

    }//GEN-LAST:event_searchlabelMouseClicked

    private void cborderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cborderItemStateChanged
        if(cborder.getSelectedItem().equals("Desc")){
            DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();
            while(model.getRowCount() > 0){
                model.removeRow(0);
            }
            try{

                Class.forName("org.sqlite.JDBC");
                con = DriverManager.getConnection("jdbc:sqlite:stu.db");
                stmt = con.createStatement();
                if(cbsort.getSelectedItem().equals("Enroll No.")){
                    String q = "Select * from stuinfo ORDER by enroll desc ;";
                    rs = stmt.executeQuery(q);
                }else if(cbsort.getSelectedItem().equals("First Name")){
                    String q = "Select * from stuinfo ORDER by first desc;";
                    rs = stmt.executeQuery(q);
                }else if(cbsort.getSelectedItem().equals("Last Name")){
                    String q = "Select * from stuinfo ORDER by last desc;";
                    rs = stmt.executeQuery(q);
                }else{
                    JOptionPane.showMessageDialog(null,"Select sort by what and then order (asc/desc)");
                }
                while(rs.next()){
                    String enroll= rs.getString("enroll");
                    String first= rs.getString("first");
                    String last= rs.getString("last");
                    String sem= rs.getString("sem");
                    String phone= rs.getString("phone");
                    String gender= rs.getString("gender");
                    String dob= rs.getString("dob");
                    String email= rs.getString("email");

                    model.addRow( new Object[] {enroll,first,last,sem,phone,gender,dob,email});
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }
                    
            finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
        }else if(cborder.getSelectedItem().equals("Asc")){
            DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();
            while(model.getRowCount() > 0){
                model.removeRow(0);
            }
            try{
                Class.forName("org.sqlite.JDBC");
                con = DriverManager.getConnection("jdbc:sqlite:stu.db");
                stmt = con.createStatement();
                if(cbsort.getSelectedItem().equals("Enroll No.")){
                    String q = "Select * from stuinfo ORDER by enroll asc ;";
                    rs = stmt.executeQuery(q);
                }else if(cbsort.getSelectedItem().equals("First Name")){
                    String q = "Select * from stuinfo ORDER by first asc;";
                    rs = stmt.executeQuery(q);
                }else if(cbsort.getSelectedItem().equals("Last Name")){
                    String q = "Select * from stuinfo ORDER by last asc;";
                    rs = stmt.executeQuery(q);
                }else{
                    JOptionPane.showMessageDialog(null,"Select sort by what and then order (asc/desc)");
                }
                while(rs.next()){
                    String enroll= rs.getString("enroll");
                    String first= rs.getString("first");
                    String last= rs.getString("last");
                    String sem= rs.getString("sem");
                    String phone= rs.getString("phone");
                    String gender= rs.getString("gender");
                    String dob= rs.getString("dob");
                    String email= rs.getString("email");

                    model.addRow( new Object[] {enroll,first,last,sem,phone,gender,dob,email});
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error in Connectivity");
            }
                    
            finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
        }
    }//GEN-LAST:event_cborderItemStateChanged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        //teacherdash w = new teacherdash();
        //w.setVisible(true);  
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit ", "Student Marks Manager" , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    DefaultTableModel model = ( DefaultTableModel ) stuinfotab.getModel();
    while(model.getRowCount() > 0){
        model.removeRow(0);
        }
    try{
        
        Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:stu.db");
        stmt = con.createStatement();
        String q = "Select * from stuinfo order by enroll ;";
        rs = stmt.executeQuery(q);
        while(rs.next()){
            String enroll= rs.getString("enroll");
            String first= rs.getString("first");
            String last= rs.getString("last");
            String sem= rs.getString("sem");
            String phone= rs.getString("phone");
            String gender= rs.getString("gender");
            String dob= rs.getString("dob");
            String email= rs.getString("email");
            
            
            model.addRow( new Object[] {enroll,first,last,sem,phone,gender,dob,email});
            }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error in Connectivity");
    }
            
          finally {
                try{
                    rs.close();
                    stmt.close();
                }
                catch(Exception e) {
                   }
        }
    
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cborder;
    private javax.swing.JComboBox<String> cbsea;
    private javax.swing.JComboBox<String> cbsem;
    private javax.swing.JComboBox<String> cbsort;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton deletebtn1;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton insertbtn;
    private javax.swing.JButton insertbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel searchlabel;
    private javax.swing.JTable stuinfotab;
    private javax.swing.JTextField tdob;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tenroll;
    private javax.swing.JTextField tfirst;
    private javax.swing.JTextField tlast;
    private javax.swing.JTextField tphone;
    private javax.swing.JTextField tsea;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
